### ISSUE TITLE
Custom themes are not working

### ISSUE THREAD

**Issue by codesimar** [kdsuneraavinash/theme_provider#11]
I added new _AppTheme_ in the _themes:_ property. But it keeps showing default dark() and light() themes. Even I tried to edit default theme constructs with _.copywith()_ method. But it's not even making changes in the default themes. I think AppTheme isn't picking up properties through _.copywith()_ method.

**Comment by kdsuneraavinash** [comment]
Can you provide a code segment with the bug? I'm not entirely sure I understand your problem.

**Comment by codesimar** [comment]
If I create a new theme, It will not work. It will keep using only default light() and dark() themes.

`themes: [
        AppTheme.light(),
        AppTheme.dark(),
        AppTheme(
          id: "custom_theme",
          description: "This is desc",
          data: ThemeData(
            primaryColor: Colors.black,
            accentColor: Colors.red,
          ),
        ),
      ],`

`onPressed: () {
                ThemeProvider.controllerOf(context).nextTheme();`

**Comment by codesimar** [comment]
It shows no error, but it shows the same default light theme in place of this custom theme `AppTheme( id: "custom_theme", description: "This is desc", data: ThemeData( primaryColor: Colors.black, accentColor: Colors.red, ), ),`

**Comment by codesimar** [comment]
Sorry, my bad. I found the mistake. I was using `backgroundColor:` in place of `scaffoldBackgroundColor` to change the background color of the app. It's working fine now. Thanks for this great package. 
Please discard this issue.
