### ISSUE TITLE
Use Default System theme when the app launches for the first time

### ISSUE THREAD

**Issue by vinoopks** [kdsuneraavinash/theme_provider#12]
Thanks for this package . This really helps!
I would love to have a feature, taking the system default theme mode when the app launches for the first time.

**Comment by kdsuneraavinash** [comment]
I think I wanted to implement this before but there was a small problem. 

Let's say you put 2 themes; blue-colored and red-colored. So which one is the default dark theme and the light theme?
So, to implement this, we have to provide two parameters on which will be the default dark theme and the default light theme. (And fallback to not using the default sys theme when neither is given)
So, there can be several edge cases around this issue.

Pull requests are welcome though :)

**Comment by vinoopks** [comment]
@kdsuneraavinash As a workaround, we can still have the feature giving conditions in `onInitCallback` of the ThemeProvider.
And for most of the business use cases, would normally be having a default light and dark theme. So, it might be a good idea to implement something. 
Thanks , will create a pull request, when I have a solid solution.

**Comment by kdsuneraavinash** [comment]
Yes, that would be great.
