### ISSUE TITLE
Question: Different theme for part of the widget tree

### ISSUE THREAD

**Issue by mploigt** [kdsuneraavinash/theme_provider#13]
If I wanted to show one rather complex widget in "dark" theme while the rest of the page is "light" (assuming I have only these two themes) how would I do that?

**Comment by mploigt** [comment]
If this package no longer maintained?

**Comment by kdsuneraavinash** [comment]
Sorry for the extremely late reply.
It should be possible using 2 theme providers using using different `providerId`s.

A test that uses this functionality can be found here.
https://github.com/kdsuneraavinash/theme_provider/blob/144c0e7ff17abf2b5c8a44116cfae1367e746d73/test/theme_provider_test.dart#L432
