### ISSUE TITLE
Current theme not being passed down correctly to material widgets

### ISSUE THREAD

**Issue by ahhmino** [kdsuneraavinash/theme_provider#16]
I noticed this issue with ```CircularProgressIndicator```, and I've seen it on both the stable and dev channels. But for a lot of the material widgets that should take in the ```accentColor``` from theme data, they don't and just revert to the default. Here's a picture of the widget tree if this helps, you can see the ```CircularProgressIndicator``` at the bottom of the screenshot of the widget tree:

![Screenshot from 2021-04-28 09-54-55](https://user-images.githubusercontent.com/38871201/116425317-d2372980-a807-11eb-90fe-9b5f5bee4f3f.png)

And I have the ```ThemeProvider```, ```ThemeConsumer```, and ```Builder``` at the root of the tree. Let me know if I'm doing something wrong! Otherwise loving the package, thank you

**Comment by kdsuneraavinash** [comment]
Will it be possible for you to share a code sample?

**Comment by ahhmino** [comment]
D'oh. I reverted back to the stable flutter channel from dev to check it again and it works now. My mistake!
