### ISSUE TITLE
Hot Reload "unloads" the current loaded Theme

### ISSUE THREAD

**Issue by wagner-rebello** [kdsuneraavinash/theme_provider#21]
When debugging the app Hot Reload revert the current selected theme to default theme.

**Comment by kdsuneraavinash** [comment]
Have you tried [persisting the theme](https://github.com/kdsuneraavinash/theme_provider#-persisting-theme)

**Comment by wagner-rebello** [comment]
I tried only `saveThemesOnChange` and didn't work.
With `loadThemeOnInit` too it works.
Thanks.
