### ISSUE TITLE
Hot reload build child widget tiwce

### ISSUE THREAD

**Issue by Dean-Spotec** [kdsuneraavinash/theme_provider#23]
if I comment `ThemeProvider.themeOf(context).data.splashColor` it just build once.
the demo you provided behave the same.
![image](https://user-images.githubusercontent.com/75231684/145799657-6850bc10-dc9a-423e-bad1-7251d8985af6.png)

**Comment by kdsuneraavinash** [comment]
Yes, I think it is building twice as expected.
The first time build is with the initial theme. But when the user saved theme is loaded (from sharedprefs) and applied, it causes another rebuild.
