### ISSUE TITLE
Plugin is broken on latest stable Flutter release

### ISSUE THREAD

**Issue by isaaclyman** [kdsuneraavinash/theme_provider#25]
Flutter 3.10 finds this plugin unable to compile. An `[ANALYSIS ISSUE]` warning is shown on pub.dev, and the following errors can be seen:

> ERROR: The named parameter 'accentColor' isn't defined.
> ERROR: The getter 'accentColor' isn't defined for the type 'ThemeData'. 

This also prevents any projects that use this plugin from building.

**Comment by kdsuneraavinash** [comment]
Thanks for letting me know, will put a fix as soon as possible

**Comment by kdsuneraavinash** [comment]
Fixed by 6.0.0
