### ISSUE TITLE
Change Default Theme Values

### ISSUE THREAD

**Issue by udaykhalsa** [kdsuneraavinash/theme_provider#6]
How can we change values of default dark and light themes?

**Comment by Azzeccagarbugli** [comment]
I would love to see this feature too!

**Comment by kdsuneraavinash** [comment]
Sorry for the extremely late reply.

As far as I understand your question, you want to change the look and feel of the pre-packaged themes.
This is actually already possible.
You can basically add new themes by providing the `theme` parameter. Use the updated light/dark themes there.

```dart
      themes: <AppTheme>[
        AppTheme(
          id: 'new_light',
          description: 'New light theme',
          data: ThemeData.light().copyWith(
            primaryColor: Colors.green,
            accentColor: Colors.yellow,
          ),
        ),
        AppTheme(
          id: 'new_dark',
          description: 'New dark theme',
          data: ThemeData.dark().copyWith(
            primaryColor: Colors.red,
            accentColor: Colors.yellow,
          ),
        ),
      ],
```

**Comment by emmggi** [comment]
Is there any way to change the ThemeData of the current theme and have changes apply to it immediately? I'm implementing a simple designer to my app where you could change basic things like ThemeData and ColorScheme.
